version: "3.8"

services:
  db:
    image: postgres:15
    container_name: store_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: store_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/store
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 1h
      PORT: 3000
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run build &&
             npm run start"

volumes:
  postgres_data:
